### ISSUE TITLE
Missing file on startup

### ISSUE THREAD

**Issue by ChrisGrigg** [jplwood/ionic2-mean-heroku-todo-app#1]
Hi there great job.

I'm noticing an error on startup where it cannot find cordova.js. It's not anywhere in the local folder either so maybe I'm misunderstanding it.

GET https://fathomless-cove-30155.herokuapp.com/cordova.js 

Thanks,

Chris

**Comment by jplwood** [comment]
Aye! I'd just been ignoring it, but thanks for reminding me. This sample app wasn't intended to [build to a device](http://ionicframework.com/docs/v2/getting-started/installation/#building-to-a-device) (yet), just to demonstrate Ionic 2/Angular 2 with a Node.js backend, pushed to Heroku. 

As such, I did remove the reference to `cordova.js` in `www/index.html` -- so future versions of the app shouldn't have this issue.
