### ISSUE TITLE
Move www resources to build

### ISSUE THREAD

**Issue by sagivf** [jplwood/ionic2-mean-heroku-todo-app#4]
OK, so I got this working on my own project but for this one I'm having issue with `typings install` not working. My projects uses Typescript 2.

Perhaps it's just better to first migrate to Typescript 2 (there will be a few easy to solve errors).

heres what I've done so far.
https://github.com/sagivf/ionic2-mean-heroku-todo-app/commits/master

**Comment by jplwood** [comment]
Thanks for doing this @sagivf ! I'll try monkeying around with it the next day or so.

**Comment by sagivf** [comment]
So far cant find an easy way to do this with ionic-app-scripts
